version: '3.7'

services:
  auth-dynamo:
    image: amazon/dynamodb-local
    container_name: auth-dynamo
    ports:
      - "8782:8000"
    expose:
      - "8000"
  auth-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    container_name: auth-api
    ports:
      - 8084:8084
